ip: 127.0.0.1
port: 23333
server-name: '生存服'
server-prefix: '§8[§a生存§8]§r'
trigger: 's'
broadcast-trigger: 'all'
fernet_key: 'mykey'
notify-on-join-and-quit: true
# in server ticks
heart-beat-interval: 900
enable-whitelist: false
# in seconds
whitelist-timeout: 1
not-whitelisted-message: '请加QQ群 594048732 自助获取白名单！'
banned-message: '你已被封禁！请加QQ群 594048732 咨询解封！'
timeout-message: '白名单认证超时，请稍后重试！'